version: "3.8"

services:
  spark-worker-b:
    image: dwad/pyspark-cluster:3.4.0
    container_name: spark-worker-b
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - ./apps:/opt/spark/apps
    networks:
      - spark_network

networks:
  spark_network:
    external: true